#pragma once
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <stack>
#include <map>
#include <unordered_map>
#include <span>
#include <memory>
#include <functional>
#include <concepts>
#include <format>
#include <chrono>
#include <numeric>
#include <numbers>
#include <algorithm>
#include <list>
#include <set>

#include "glm/glm.hpp"
#include "glm/gtc/matrix_transform.hpp"